"""
SheetCraft AI — Product 02: Annual Financial Overview
Generated by Agent: 阿財
"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.chart import BarChart, PieChart, Reference
from openpyxl.formatting.rule import CellIsRule
from openpyxl.utils import get_column_letter
import os

G = "2D5F2D"; C = "F5F0E8"; GO = "D4A574"; D = "1A1A1A"; W = "FFFFFF"; LG = "E8F0E8"; R = "CC4444"; LR = "FFE0E0"
HF = Font(name="Calibri", size=14, bold=True, color=W)
SF = Font(name="Calibri", size=11, bold=True, color=G)
NF = Font(name="Calibri", size=11, color=D)
MF = '#,##0.00'; PF = '0.0%'
GF = PatternFill(start_color=G, end_color=G, fill_type="solid")
CF = PatternFill(start_color=C, end_color=C, fill_type="solid")
WF = PatternFill(start_color=W, end_color=W, fill_type="solid")
LGF = PatternFill(start_color=LG, end_color=LG, fill_type="solid")
GOF = PatternFill(start_color=GO, end_color=GO, fill_type="solid")
TB = Border(left=Side(style="thin",color="CCCCCC"),right=Side(style="thin",color="CCCCCC"),top=Side(style="thin",color="CCCCCC"),bottom=Side(style="thin",color="CCCCCC"))
CT = Alignment(horizontal="center", vertical="center")
LT = Alignment(horizontal="left", vertical="center")
WR = Alignment(horizontal="left", vertical="top", wrap_text=True)

def sc(cell, font=None, fill=None, align=None, nf=None):
    if font: cell.font = font
    if fill: cell.fill = fill
    if align: cell.alignment = align
    if nf: cell.number_format = nf
    cell.border = TB

def title_row(ws, row, text, max_col):
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=max_col)
    cell = ws.cell(row=row, column=1, value=text)
    sc(cell, Font(name="Calibri",size=18,bold=True,color=W), GF, CT)
    for c in range(2, max_col+1): sc(ws.cell(row=row,column=c), fill=GF)

def header_row(ws, row, headers):
    for i, h in enumerate(headers, 1):
        cell = ws.cell(row=row, column=i, value=h)
        sc(cell, Font(name="Calibri",size=11,bold=True,color=W), GF, CT)

def create_monthly_summary(wb):
    ws = wb.create_sheet("Monthly Summary")
    for c in range(1,15): ws.column_dimensions[get_column_letter(c)].width = 16
    title_row(ws, 1, "MONTHLY FINANCIAL SUMMARY 2026", 7)
    headers = ["Month","Income","Fixed Expenses","Variable Expenses","Total Expenses","Savings","Net"]
    header_row(ws, 3, headers)
    months = ["January","February","March","April","May","June","July","August","September","October","November","December"]
    sample_income = [5000,5000,5200,5000,5500,5000,5000,5200,5000,5000,5500,6000]
    sample_fixed = [2200,2200,2200,2200,2200,2200,2200,2200,2200,2200,2200,2200]
    sample_var = [1200,1100,1350,1000,1400,1150,1300,1250,1100,1200,1500,1800]
    for i, m in enumerate(months):
        r = 4 + i
        ws.cell(row=r,column=1,value=m)
        ws.cell(row=r,column=2,value=sample_income[i])
        ws.cell(row=r,column=3,value=sample_fixed[i])
        ws.cell(row=r,column=4,value=sample_var[i])
        ws.cell(row=r,column=5).value = f"=C{r}+D{r}"
        ws.cell(row=r,column=6).value = f"=B{r}-E{r}"
        ws.cell(row=r,column=7).value = f"=IF(B{r}>0,F{r}/B{r},0)"
        fill = CF if i%2==0 else WF
        for c in range(1,8):
            fmt = PF if c==7 else (MF if c>1 else None)
            sc(ws.cell(row=r,column=c), NF, fill, CT, fmt)
    tr = 16
    ws.cell(row=tr,column=1,value="TOTAL")
    for c in range(2,7):
        ws.cell(row=tr,column=c).value = f"=SUM({get_column_letter(c)}4:{get_column_letter(c)}15)"
    ws.cell(row=tr,column=7).value = "=IF(B16>0,F16/B16,0)"
    for c in range(1,8):
        fmt = PF if c==7 else (MF if c>1 else None)
        sc(ws.cell(row=tr,column=c), Font(name="Calibri",size=11,bold=True,color=G), LGF, CT, fmt)
    ws.conditional_formatting.add(f"F4:F15", CellIsRule(operator="lessThan",formula=["0"],fill=PatternFill(start_color=LR,end_color=LR,fill_type="solid"),font=Font(color=R,bold=True)))
    bar = BarChart(); bar.type="col"; bar.title="Monthly Income vs Expenses"; bar.style=10
    cats = Reference(ws,min_col=1,min_row=4,max_row=15)
    d1 = Reference(ws,min_col=2,min_row=3,max_row=15)
    d2 = Reference(ws,min_col=5,min_row=3,max_row=15)
    bar.add_data(d1,titles_from_data=True); bar.add_data(d2,titles_from_data=True)
    bar.set_categories(cats); bar.width=22; bar.height=12
    ws.add_chart(bar, "A19")

def create_net_worth(wb):
    ws = wb.create_sheet("Net Worth")
    ws.column_dimensions["A"].width = 25; ws.column_dimensions["B"].width = 18; ws.column_dimensions["C"].width = 18
    title_row(ws, 1, "NET WORTH TRACKER", 3)
    ws.cell(row=3,column=1,value="ASSETS"); sc(ws.cell(row=3,column=1),Font(name="Calibri",size=13,bold=True,color=W),GF,CT)
    ws.cell(row=3,column=2,value="Category"); sc(ws.cell(row=3,column=2),Font(name="Calibri",size=11,bold=True,color=W),GF,CT)
    ws.cell(row=3,column=3,value="Value"); sc(ws.cell(row=3,column=3),Font(name="Calibri",size=11,bold=True,color=W),GF,CT)
    assets = [("Checking Account","Cash",8500),("Savings Account","Cash",15000),("Emergency Fund","Cash",10000),("401(k)","Investments",45000),("Brokerage Account","Investments",12000),("Crypto","Investments",3000),("Home Value","Property",350000),("Car Value","Property",18000)]
    for i,(name,cat,val) in enumerate(assets):
        r=4+i; fill=CF if i%2==0 else WF
        ws.cell(row=r,column=1,value=name); ws.cell(row=r,column=2,value=cat); ws.cell(row=r,column=3,value=val)
        for c in range(1,4): sc(ws.cell(row=r,column=c),NF,fill,CT if c>1 else LT,MF if c==3 else None)
    ar=4+len(assets)
    ws.cell(row=ar,column=1,value="TOTAL ASSETS")
    ws.cell(row=ar,column=3).value=f"=SUM(C4:C{ar-1})"
    for c in range(1,4): sc(ws.cell(row=ar,column=c),Font(name="Calibri",size=11,bold=True,color=G),LGF,CT,MF if c==3 else None)
    lr=ar+2
    ws.cell(row=lr,column=1,value="LIABILITIES"); sc(ws.cell(row=lr,column=1),Font(name="Calibri",size=13,bold=True,color=W),PatternFill(start_color=R,end_color=R,fill_type="solid"),CT)
    ws.cell(row=lr,column=2,value="Category"); sc(ws.cell(row=lr,column=2),Font(name="Calibri",size=11,bold=True,color=W),PatternFill(start_color=R,end_color=R,fill_type="solid"),CT)
    ws.cell(row=lr,column=3,value="Balance"); sc(ws.cell(row=lr,column=3),Font(name="Calibri",size=11,bold=True,color=W),PatternFill(start_color=R,end_color=R,fill_type="solid"),CT)
    liabilities=[("Mortgage","Loan",280000),("Car Loan","Loan",12000),("Student Loan","Loan",25000),("Credit Card 1","Credit Card",3500),("Credit Card 2","Credit Card",1200)]
    for i,(name,cat,val) in enumerate(liabilities):
        r=lr+1+i; fill=CF if i%2==0 else WF
        ws.cell(row=r,column=1,value=name); ws.cell(row=r,column=2,value=cat); ws.cell(row=r,column=3,value=val)
        for c in range(1,4): sc(ws.cell(row=r,column=c),NF,fill,CT if c>1 else LT,MF if c==3 else None)
    tlr=lr+1+len(liabilities)
    ws.cell(row=tlr,column=1,value="TOTAL LIABILITIES")
    ws.cell(row=tlr,column=3).value=f"=SUM(C{lr+1}:C{tlr-1})"
    for c in range(1,4): sc(ws.cell(row=tlr,column=c),Font(name="Calibri",size=11,bold=True,color=R),PatternFill(start_color=LR,end_color=LR,fill_type="solid"),CT,MF if c==3 else None)
    nwr=tlr+2
    ws.cell(row=nwr,column=1,value="NET WORTH")
    ws.cell(row=nwr,column=3).value=f"=C{ar}-C{tlr}"
    for c in range(1,4): sc(ws.cell(row=nwr,column=c),Font(name="Calibri",size=14,bold=True,color=G),LGF,CT,MF if c==3 else None)
    pie=PieChart(); pie.title="Asset Allocation"; pie.style=10
    cats=Reference(ws,min_col=1,min_row=4,max_row=ar-1)
    data=Reference(ws,min_col=3,min_row=3,max_row=ar-1)
    pie.add_data(data,titles_from_data=True); pie.set_categories(cats); pie.width=16; pie.height=10
    ws.add_chart(pie,f"A{nwr+3}")

def create_investments(wb):
    ws = wb.create_sheet("Investments")
    cols = ["Name","Ticker","Shares","Buy Price","Current Price","Market Value","Gain/Loss $","Gain/Loss %","Allocation %"]
    for i in range(len(cols)): ws.column_dimensions[get_column_letter(i+1)].width = 16
    title_row(ws, 1, "INVESTMENT PORTFOLIO", len(cols))
    header_row(ws, 3, cols)
    stocks=[("S&P 500 ETF","VOO",50,380.00,420.50),("Total Market ETF","VTI",30,210.00,228.75),("Tech ETF","QQQ",20,350.00,385.00),("Bond ETF","BND",40,72.00,70.50),("Int'l ETF","VXUS",25,55.00,58.20),("REIT ETF","VNQ",15,85.00,82.00),("Dividend ETF","VYM",35,110.00,118.50)]
    for i,(name,ticker,shares,buy,cur) in enumerate(stocks):
        r=4+i; fill=CF if i%2==0 else WF
        ws.cell(row=r,column=1,value=name); ws.cell(row=r,column=2,value=ticker); ws.cell(row=r,column=3,value=shares)
        ws.cell(row=r,column=4,value=buy); ws.cell(row=r,column=5,value=cur)
        ws.cell(row=r,column=6).value=f"=C{r}*E{r}"
        ws.cell(row=r,column=7).value=f"=F{r}-(C{r}*D{r})"
        ws.cell(row=r,column=8).value=f"=IF(C{r}*D{r}>0,G{r}/(C{r}*D{r}),0)"
        ws.cell(row=r,column=9).value=f"=IF(F${ 4+len(stocks)}>0,F{r}/F${4+len(stocks)},0)"
        for c in range(1,10):
            fmt = MF if c in(4,5,6,7) else (PF if c in(8,9) else None)
            sc(ws.cell(row=r,column=c),NF,fill,CT if c>1 else LT,fmt)
    tr=4+len(stocks)
    ws.cell(row=tr,column=1,value="TOTAL PORTFOLIO")
    for c in [3,6,7]:
        ws.cell(row=tr,column=c).value=f"=SUM({get_column_letter(c)}4:{get_column_letter(c)}{tr-1})"
    ws.cell(row=tr,column=8).value=f"=IF((SUMPRODUCT(C4:C{tr-1},D4:D{tr-1}))>0,G{tr}/SUMPRODUCT(C4:C{tr-1},D4:D{tr-1}),0)"
    for c in range(1,10):
        fmt = MF if c in(4,5,6,7) else (PF if c in(8,9) else None)
        sc(ws.cell(row=tr,column=c),Font(name="Calibri",size=11,bold=True,color=G),LGF,CT,fmt)
    ws.conditional_formatting.add(f"G4:G{tr-1}",CellIsRule(operator="lessThan",formula=["0"],fill=PatternFill(start_color=LR,end_color=LR,fill_type="solid"),font=Font(color=R)))
    ws.conditional_formatting.add(f"G4:G{tr-1}",CellIsRule(operator="greaterThan",formula=["0"],fill=PatternFill(start_color=LG,end_color=LG,fill_type="solid"),font=Font(color=G)))
    pie=PieChart(); pie.title="Portfolio Allocation"; pie.style=10
    cats=Reference(ws,min_col=1,min_row=4,max_row=tr-1)
    data=Reference(ws,min_col=6,min_row=3,max_row=tr-1)
    pie.add_data(data,titles_from_data=True); pie.set_categories(cats); pie.width=16; pie.height=10
    ws.add_chart(pie,f"A{tr+3}")

def create_goals(wb):
    ws = wb.create_sheet("Goals")
    cols=["Goal","Target Amount","Current Amount","Remaining","Progress %","Target Date","Status"]
    for i in range(len(cols)): ws.column_dimensions[get_column_letter(i+1)].width = 18
    title_row(ws, 1, "FINANCIAL GOALS TRACKER", len(cols))
    header_row(ws, 3, cols)
    goals=[("Emergency Fund (6 months)",30000,10000,"2026-12-31"),("House Down Payment",60000,15000,"2028-06-30"),("Vacation Fund",5000,3200,"2026-08-31"),("New Car Fund",25000,8000,"2027-12-31"),("Retirement Milestone",500000,45000,"2045-12-31"),("Pay Off Student Loans",25000,18000,"2027-06-30"),("Start a Business",20000,4500,"2028-12-31")]
    for i,(goal,target,current,date) in enumerate(goals):
        r=4+i; fill=CF if i%2==0 else WF
        ws.cell(row=r,column=1,value=goal); ws.cell(row=r,column=2,value=target); ws.cell(row=r,column=3,value=current)
        ws.cell(row=r,column=4).value=f"=B{r}-C{r}"
        ws.cell(row=r,column=5).value=f"=IF(B{r}>0,C{r}/B{r},0)"
        ws.cell(row=r,column=6,value=date)
        ws.cell(row=r,column=7).value=f'=IF(E{r}>=1,"Completed",IF(E{r}>=0.5,"On Track","Behind"))'
        for c in range(1,8):
            fmt = MF if c in(2,3,4) else (PF if c==5 else None)
            sc(ws.cell(row=r,column=c),NF,fill,CT if c>1 else LT,fmt)
    lr=4+len(goals)-1
    ws.conditional_formatting.add(f"E4:E{lr}",CellIsRule(operator="greaterThanOrEqual",formula=["0.75"],fill=PatternFill(start_color=LG,end_color=LG,fill_type="solid"),font=Font(color=G,bold=True)))
    ws.conditional_formatting.add(f"E4:E{lr}",CellIsRule(operator="lessThan",formula=["0.25"],fill=PatternFill(start_color=LR,end_color=LR,fill_type="solid"),font=Font(color=R)))

def create_dashboard(wb):
    ws = wb.create_sheet("Dashboard")
    for c in range(1,9): ws.column_dimensions[get_column_letter(c)].width = 18
    title_row(ws, 1, "ANNUAL FINANCIAL OVERVIEW 2026", 8)
    cards=[("Total Income","='Monthly Summary'!B16"),("Total Expenses","='Monthly Summary'!E16"),("Total Savings","='Monthly Summary'!F16"),("Savings Rate","=IF(B4>0,D4/B4,0)")]
    for i,(label,formula) in enumerate(cards):
        col=i*2+1
        ws.cell(row=3,column=col,value=label); sc(ws.cell(row=3,column=col),Font(name="Calibri",size=10,bold=True,color=W),GF,CT)
        ws.cell(row=3,column=col+1); sc(ws.cell(row=3,column=col+1),fill=GF)
        ws.cell(row=4,column=col,value=formula)
        fmt=PF if i==3 else MF
        sc(ws.cell(row=4,column=col),Font(name="Calibri",size=16,bold=True,color=D),CF,CT,fmt)
        sc(ws.cell(row=4,column=col+1),fill=CF)
    ws.cell(row=6,column=1,value="Net Worth"); sc(ws.cell(row=6,column=1),SF,LGF,LT)
    ws.cell(row=6,column=2,value="='Net Worth'!C"+str(20)); sc(ws.cell(row=6,column=2),Font(name="Calibri",size=14,bold=True,color=G),LGF,CT,MF)

def create_instructions(wb):
    ws = wb.create_sheet("Instructions")
    ws.column_dimensions["A"].width=5; ws.column_dimensions["B"].width=80
    title_row(ws, 1, "HOW TO USE YOUR ANNUAL FINANCIAL OVERVIEW", 2)
    items=[
        ("Getting Started",["1. Go to 'Monthly Summary' and review/update your monthly income and expenses","2. Update 'Net Worth' with your current asset values and liability balances","3. Add your investment holdings in the 'Investments' tab","4. Set your financial goals in the 'Goals' tab","5. Check your Dashboard for the complete overview!"]),
        ("Monthly Routine",["- Update your income and expenses in Monthly Summary each month","- Review your Net Worth quarterly (update asset/liability values)","- Update investment prices monthly or quarterly","- Check goal progress and adjust savings accordingly"]),
        ("Tips",["- All green cells contain formulas — don't edit them!","- Make a backup copy before major changes","- Use conditional formatting colors as guides (red=attention needed, green=on track)","- Update investment prices from your brokerage account"]),
        ("Need Help?",["Message us on Etsy — we typically reply within a few hours!","Thank you for your purchase!"])
    ]
    row=3
    for title,lines in items:
        ws.cell(row=row,column=2,value=title); sc(ws.cell(row=row,column=2),Font(name="Calibri",size=13,bold=True,color=G),LGF,LT)
        row+=1
        for line in lines:
            ws.cell(row=row,column=2,value=line); sc(ws.cell(row=row,column=2),NF,WF,WR); ws.row_dimensions[row].height=22; row+=1
        row+=1

def generate():
    wb = openpyxl.Workbook(); wb.remove(wb.active)
    create_monthly_summary(wb); create_net_worth(wb); create_investments(wb); create_goals(wb)
    create_dashboard(wb); create_instructions(wb)
    order=["Dashboard","Monthly Summary","Net Worth","Investments","Goals","Instructions"]
    for i,name in enumerate(order): wb.move_sheet(name, offset=i-wb.sheetnames.index(name))
    out=os.path.join(os.path.dirname(os.path.abspath(__file__)),"Annual_Financial_Overview_SheetCraft.xlsx")
    wb.save(out); print(f"Generated: {out}"); return out

if __name__=="__main__": generate()
